<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.streamx.blueprints</groupId>
    <artifactId>services</artifactId>
    <version>3.0.1-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>processing</artifactId>
  <name>Blueprints : Processing Services</name>
  <packaging>pom</packaging>

  <modules>
    <module>composition-engine</module>
    <module>data-collector</module>
    <module>event-converter</module>
    <module>external-references-rewriter</module>
    <module>indexable-resources-producer</module>
    <module>integration-test-commons</module>
    <module>json-aggregator</module>
    <module>local-references-rewriter</module>
    <module>optimized-images-generator</module>
    <module>rendering-engine</module>
    <module>resource-downloader</module>
    <module>sitemap-generator</module>
  </modules>

  <dependencies>
    <dependency>
      <groupId>com.streamx.blueprints</groupId>
      <artifactId>integration-test-commons</artifactId>
      <version>${project.version}</version>
      <classifier>tests</classifier>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkiverse.wiremock</groupId>
      <artifactId>quarkus-wiremock-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

</project>
