quarkus.otel.traces.exporter=none

mp.messaging.incoming.resources.connector=quarkus-http
mp.messaging.incoming.resources.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.resources.path=/resources
mp.messaging.incoming.resources.protocolVersion=HTTP_2
mp.messaging.incoming.resources.twoPhaseResponseFlow=true

streamx.url-include-replacement-provider=SsiInclude
streamx.blueprints.web-server-sink.html-resource-types=\
com.streamx.blueprints.page.published.v1,\
com.streamx.blueprints.page.unpublished.v1,\
com.streamx.blueprints.fragment.published.v1,\
com.streamx.blueprints.fragment.unpublished.v1