quarkus.otel.traces.exporter=none

mp.messaging.incoming.indexable-resources.connector=quarkus-http
mp.messaging.incoming.indexable-resources.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.indexable-resources.path=/indexable-resources
mp.messaging.incoming.indexable-resources.protocolVersion=HTTP_2
mp.messaging.incoming.indexable-resources.twoPhaseResponseFlow=true

mp.messaging.incoming.indexable-resource-fragments.connector=quarkus-http
mp.messaging.incoming.indexable-resource-fragments.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.indexable-resource-fragments.path=/indexable-resource-fragments
mp.messaging.incoming.indexable-resource-fragments.protocolVersion=HTTP_2
mp.messaging.incoming.indexable-resource-fragments.twoPhaseResponseFlow=true

mp.messaging.incoming.indexable-resource-fragments-state.connector=quarkus-http
mp.messaging.incoming.indexable-resource-fragments-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.indexable-resource-fragments-state.path=/indexable-resource-fragments-state
mp.messaging.incoming.indexable-resource-fragments-state.protocolVersion=HTTP_2
mp.messaging.incoming.indexable-resource-fragments-state.twoPhaseResponseFlow=true

streamx.blueprints.opensearch-sink.allowed-json-paths=\
took,\
timed_out,\
hits.max_score,\
hits.total..*,\
hits.hits.*['_id'],\
hits.hits.*['_score'],\
hits.hits.*['_source']..*,\
hits.hits.*.highlight..*,\
aggregations..*

# List of classes that should not be initialized at build time in the native mode (moves their initialization to runtime)
quarkus.native.additional-build-args=--initialize-at-run-time=com.senacor.elasticsearch.evolution.core.internal.utils.RandomUtils
