streamx.blueprints.indexable-resources-producer.index-fragments=false

%dev.mp.messaging.incoming.pages.topic=persistent://public/default/pages
%dev.mp.messaging.outgoing.indexable-resources.topic=persistent://public/default/indexable-resources
