streamx.blueprints.indexable-resources-producer.index-fragments=false

mp.messaging.incoming.pages.connector=quarkus-http
mp.messaging.incoming.pages.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.pages.path=/pages

mp.messaging.incoming.fragments.connector=quarkus-http
mp.messaging.incoming.fragments.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.fragments.path=/fragments

mp.messaging.outgoing.indexable-resources.connector=quarkus-http
mp.messaging.outgoing.indexable-resources.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.indexable-resources.url=${STREAMX_ENDPOINT_INDEXABLE_RESOURCES}

mp.messaging.outgoing.indexable-resource-fragments.connector=quarkus-http
mp.messaging.outgoing.indexable-resource-fragments.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.indexable-resource-fragments.url=${STREAMX_ENDPOINT_INDEXABLE_RESOURCE_FRAGMENTS}