quarkus.otel.traces.exporter=none

mp.messaging.incoming.incoming-resources.connector=quarkus-http
mp.messaging.incoming.incoming-resources.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.incoming-resources.path=/incoming-resources

mp.messaging.outgoing.outgoing-resources.connector=quarkus-http
mp.messaging.outgoing.outgoing-resources.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.outgoing-resources.url=${STREAMX_ENDPOINT_OUTGOING_RESOURCES}
mp.messaging.outgoing.outgoing-resources.maxInflightMessages=1000

mp.messaging.outgoing.download-requests.connector=quarkus-http
mp.messaging.outgoing.download-requests.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.download-requests.url=${STREAMX_ENDPOINT_DOWNLOAD_REQUESTS}
mp.messaging.outgoing.download-requests.maxInflightMessages=1000