mp.messaging.outgoing.outgoing-resources.merge=true

mp.messaging.incoming.incoming-resources.connector=quarkus-http
mp.messaging.incoming.incoming-resources.deserializer=dev.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.incoming-resources.path=/resources

mp.messaging.outgoing.outgoing-resources.connector=quarkus-http
mp.messaging.outgoing.outgoing-resources.serializer=dev.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.outgoing-resources.url=http://localhost:8080/resources