mp.messaging.incoming.download-requests.connector=quarkus-http
mp.messaging.incoming.download-requests.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.download-requests.path=/download-requests

mp.messaging.outgoing.downloaded-resources.connector=quarkus-http
mp.messaging.outgoing.downloaded-resources.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.downloaded-resources.url=${STREAMX_ENDPOINT_DOWNLOADED_RESOURCES}