quarkus.native.additional-build-args=--enable-url-protocols=https
quarkus.otel.traces.exporter=none

mp.messaging.incoming.download-requests.connector=quarkus-http
mp.messaging.incoming.download-requests.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.download-requests.path=/download-requests
mp.messaging.incoming.download-requests.protocolVersion=HTTP_2
mp.messaging.incoming.download-requests.twoPhaseResponseFlow=true

mp.messaging.incoming.download-requests-state.connector=quarkus-http
mp.messaging.incoming.download-requests-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.download-requests-state.path=/download-requests-state
mp.messaging.incoming.download-requests-state.protocolVersion=HTTP_2
mp.messaging.incoming.download-requests-state.twoPhaseResponseFlow=true

mp.messaging.outgoing.downloaded-pages.connector=quarkus-http
mp.messaging.outgoing.downloaded-pages.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.downloaded-pages.url=${STREAMX_ENDPOINT_DOWNLOADED_PAGES}
mp.messaging.outgoing.downloaded-pages.protocolVersion=HTTP_2
mp.messaging.outgoing.downloaded-pages.twoPhaseResponseFlow=true

mp.messaging.outgoing.downloaded-assets.connector=quarkus-http
mp.messaging.outgoing.downloaded-assets.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.downloaded-assets.url=${STREAMX_ENDPOINT_DOWNLOADED_ASSETS}
mp.messaging.outgoing.downloaded-assets.protocolVersion=HTTP_2
mp.messaging.outgoing.downloaded-assets.twoPhaseResponseFlow=true

mp.messaging.outgoing.downloaded-web-resources.connector=quarkus-http
mp.messaging.outgoing.downloaded-web-resources.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.downloaded-web-resources.url=${STREAMX_ENDPOINT_DOWNLOADED_WEB_RESOURCES}
mp.messaging.outgoing.downloaded-web-resources.protocolVersion=HTTP_2
mp.messaging.outgoing.downloaded-web-resources.twoPhaseResponseFlow=true

mp.messaging.outgoing.downloaded-assets.merge=true
mp.messaging.outgoing.downloaded-web-resources.merge=true
mp.messaging.outgoing.downloaded-pages.merge=true