quarkus.otel.traces.exporter=none

mp.messaging.incoming.download-requests.connector=quarkus-websocket
mp.messaging.incoming.download-requests.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.download-requests.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.download-requests.path=/download-requests

mp.messaging.incoming.download-requests-state.connector=quarkus-websocket
mp.messaging.incoming.download-requests-state.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.download-requests-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.download-requests-state.path=/download-requests-state

mp.messaging.outgoing.downloaded-pages.connector=quarkus-websocket
mp.messaging.outgoing.downloaded-pages.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.outgoing.downloaded-pages.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.downloaded-pages.url=${STREAMX_ENDPOINT_DOWNLOADED_PAGES}

mp.messaging.outgoing.downloaded-assets.connector=quarkus-websocket
mp.messaging.outgoing.downloaded-assets.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.outgoing.downloaded-assets.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.downloaded-assets.url=${STREAMX_ENDPOINT_DOWNLOADED_ASSETS}

mp.messaging.outgoing.downloaded-web-resources.connector=quarkus-websocket
mp.messaging.outgoing.downloaded-web-resources.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.outgoing.downloaded-web-resources.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.downloaded-web-resources.url=${STREAMX_ENDPOINT_DOWNLOADED_WEB_RESOURCES}

mp.messaging.outgoing.downloaded-assets.merge=true
mp.messaging.outgoing.downloaded-web-resources.merge=true
mp.messaging.outgoing.downloaded-pages.merge=true