%dev.mp.messaging.incoming.incoming-assets.topic=persistent://public/default/assets
%dev.mp.messaging.outgoing.optimized-assets.topic=persistent://public/default/assets

%dev.mp.messaging.incoming.incoming-pages.topic=persistent://public/default/pages
%dev.mp.messaging.outgoing.outgoing-pages.topic=persistent://public/default/pages

# Error optimizing an asset is most likely unrecoverable (e.g. it's not a valid image etc.)
mp.messaging.incoming.incoming-assets.deadLetterPolicy.maxRedeliverCount=1

%dev.streamx.blueprints.image-optimization-processing-service.optimized-file-paths-pattern=.*(png|gif|jpg|jpeg)$
%dev.streamx.blueprints.image-optimization-processing-service.optimized-image-file-name-suffix=-optimized
%dev.streamx.blueprints.image-optimization-processing-service.adjusted-page-paths-pattern=.*
%dev.streamx.blueprints.image-optimization-processing-service.webp-conversion-speed=6
%dev.streamx.blueprints.image-optimization-processing-service.webp-conversion-quality=75
%dev.streamx.blueprints.image-optimization-processing-service.webp-conversion-method=4
%dev.streamx.blueprints.image-optimization-processing-service.webp-conversion-lossless=false
%dev.streamx.blueprints.image-optimization-processing-service.webp-conversion-no-alpha=false
%dev.streamx.blueprints.image-optimization-processing-service.webp-conversion-multi-thread=false
