<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.streamx.blueprints</groupId>
    <artifactId>processing</artifactId>
    <version>3.0.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>image-optimizer</artifactId>
  <name>StreamX Blueprints : Image Optimizer</name>

  <properties>
    <scrimage-webp.version>4.1.3</scrimage-webp.version>
    <jsoup.version>1.16.1</jsoup.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.streamx</groupId>
      <artifactId>reactive-messaging-http-cloudevents</artifactId>
    </dependency>
    <dependency>
      <groupId>com.streamx.blueprints</groupId>
      <artifactId>data-model</artifactId>
    </dependency>
    <dependency>
      <groupId>com.streamx.blueprints</groupId>
      <artifactId>cloud-events-support</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sksamuel.scrimage</groupId>
      <artifactId>scrimage-webp</artifactId>
      <version>${scrimage-webp.version}</version>
    </dependency>
    <dependency>
      <groupId>org.jsoup</groupId>
      <artifactId>jsoup</artifactId>
      <version>${jsoup.version}</version>
    </dependency>

    <!-- Test dependencies -->
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5-mockito</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-params</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.awaitility</groupId>
      <artifactId>awaitility</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-reactive-messaging-in-memory</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
