<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.streamx.blueprints</groupId>
    <artifactId>processing</artifactId>
    <version>3.0.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>image-optimizer</artifactId>
  <name>StreamX Blueprints : Image Optimizer</name>

  <properties>
    <scrimage-webp.version>4.3.5</scrimage-webp.version>
    <jsoup.version>1.21.2</jsoup.version>
    <maven-dependency-plugin.version>3.9.0</maven-dependency-plugin.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.sksamuel.scrimage</groupId>
      <artifactId>scrimage-webp</artifactId>
      <version>${scrimage-webp.version}</version>
    </dependency>
    <dependency>
      <groupId>org.jsoup</groupId>
      <artifactId>jsoup</artifactId>
      <version>${jsoup.version}</version>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <dependencies>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-awt</artifactId>
        </dependency>
      </dependencies>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>${maven-dependency-plugin.version}</version>
            <executions>
              <execution>
                <id>unpack-binaries</id>
                <phase>prepare-package</phase>
                <goals>
                  <goal>unpack</goal>
                </goals>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>com.sksamuel.scrimage</groupId>
                      <artifactId>scrimage-webp</artifactId>
                      <includes>dist_webp_binaries/libwebp-1.4.0-linux-aarch64/bin/*</includes>
                      <outputDirectory>${project.build.directory}/scrimage-webp-libraries</outputDirectory>
                    </artifactItem>
                  </artifactItems>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

</project>
