# Error optimizing an asset is most likely unrecoverable (e.g. it's not a valid image etc.)
mp.messaging.incoming.incoming-resources.deadLetterPolicy.maxRedeliverCount=1

# Both functions that accept page to be adjusted and image to be optimized, use the same incoming channel
mp.messaging.incoming.incoming-resources.broadcast=true

mp.messaging.incoming.incoming-resources.connector=quarkus-http
mp.messaging.incoming.incoming-resources.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.incoming-resources.path=/incoming-resources

mp.messaging.outgoing.outgoing-resources.connector=quarkus-http
mp.messaging.outgoing.outgoing-resources.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.outgoing-resources.url=${STREAMX_ENDPOINT_OUTGOING_RESOURCES}

mp.messaging.outgoing.optimized-assets.connector=quarkus-http
mp.messaging.outgoing.optimized-assets.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.optimized-assets.url=${STREAMX_ENDPOINT_OPTIMIZED_ASSETS}
