mp.messaging.incoming.incoming-assets.connector=quarkus-http
mp.messaging.incoming.incoming-assets.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.incoming-assets.path=/incoming-assets

mp.messaging.outgoing.optimized-assets.connector=quarkus-http
mp.messaging.outgoing.optimized-assets.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.optimized-assets.url=${STREAMX_ENDPOINT_OPTIMIZED_ASSETS}

mp.messaging.incoming.incoming-pages.connector=quarkus-http
mp.messaging.incoming.incoming-pages.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.incoming-pages.path=/incoming-pages

mp.messaging.outgoing.outgoing-pages.connector=quarkus-http
mp.messaging.outgoing.outgoing-pages.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.outgoing-pages.url=${STREAMX_ENDPOINT_OUTGOING_PAGES}

# These classes must be initialized at runtime (since they read a system property in static init block) instead of while building the native image before running it
quarkus.native.additional-build-args=--initialize-at-run-time=com.sksamuel.scrimage