streamx.blueprints.opensearch-sink.allowed-json-paths=\
took,\
timed_out,\
hits.max_score,\
hits.total..*,\
hits.hits.*['_id'],\
hits.hits.*['_score'],\
hits.hits.*['_source']..*,\
hits.hits.*.highlight..*,\
aggregations..*

quarkus.elasticsearch.devservices.distribution=opensearch
quarkus.elasticsearch.devservices.image-name=docker.io/opensearchproject/opensearch:2.16.0
quarkus.elasticsearch.devservices.reuse=false

%streamx-mesh-dev.quarkus.http.port=8082
%streamx-mesh-dev.quarkus.pulsar.devservices.enabled=false
%streamx-mesh-dev.pulsar.client.serviceUrl=pulsar://localhost:6650
%streamx-mesh-dev.quarkus.elasticsearch.devservices.port=9200
%streamx-mesh-dev.mp.messaging.incoming.indexable-resources.topic=persistent://streamx/outboxes/indexable-resources
%streamx-mesh-dev.mp.messaging.incoming.indexable-resource-fragments.topic=persistent://streamx/outboxes/indexable-resource-fragments

%instance-dev.mp.messaging.incoming.indexable-resources.topic=persistent://public/default/indexable-resources
%instance-dev.mp.messaging.incoming.indexable-resource-fragments.topic=persistent://public/default/indexable-resource-fragments

#%dev.quarkus.config.profile.parent=streamx-mesh-dev
%dev.quarkus.config.profile.parent=instance-dev