quarkus.otel.traces.exporter=none

mp.messaging.incoming.resources.connector=quarkus-http
mp.messaging.incoming.resources.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.resources.path=/resources
mp.messaging.incoming.resources.protocolVersion=HTTP_2
mp.messaging.incoming.resources.twoPhaseResponseFlow=true

mp.messaging.outgoing.indexable-resources.connector=quarkus-http
mp.messaging.outgoing.indexable-resources.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.indexable-resources.url=${STREAMX_ENDPOINT_INDEXABLE_RESOURCES}
mp.messaging.outgoing.indexable-resources.protocolVersion=HTTP_2
mp.messaging.outgoing.indexable-resources.twoPhaseResponseFlow=true