streamx.blueprints.sitemap-generator-processing-service.generate-lastmod-attribute=false
streamx.blueprints.sitemap-generator-processing-service.dirty-check.interval=5s
streamx.blueprints.sitemap-generator-processing-service.dirty-check.delay=10s
streamx.blueprints.sitemap-generator-processing-service.dirty-check.max-dirty-sequence-count=12

%dev.streamx.blueprints.sitemap-generator-processing-service.output-key=sitemap.xml
%dev.streamx.blueprints.sitemap-generator-processing-service.base-url=http://localhost:8081

%dev.mp.messaging.incoming.incoming-pages.topic=persistent://streamx/inboxes/pages
%dev.mp.messaging.outgoing.outgoing-sitemaps.topic=persistent://streamx/outboxes/web-resources
