quarkus.otel.traces.exporter=none

streamx.blueprints.sitemap-generator.generate-lastmod-attribute=false
streamx.blueprints.sitemap-generator.dirty-check.interval=5s
streamx.blueprints.sitemap-generator.dirty-check.delay=10s
streamx.blueprints.sitemap-generator.dirty-check.max-dirty-sequence-count=12

mp.messaging.incoming.incoming-pages.connector=quarkus-websocket
mp.messaging.incoming.incoming-pages.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.incoming-pages.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.incoming-pages.path=/incoming-pages

mp.messaging.incoming.incoming-pages-state.connector=quarkus-websocket
mp.messaging.incoming.incoming-pages-state.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.incoming-pages-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.incoming-pages-state.path=/incoming-pages-state

mp.messaging.outgoing.outgoing-sitemaps.connector=quarkus-websocket
mp.messaging.outgoing.outgoing-sitemaps.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.outgoing.outgoing-sitemaps.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.outgoing-sitemaps.url=${STREAMX_ENDPOINT_OUTGOING_SITEMAPS}

# Required to fix the exception that happens during the service execution in native mode:
#  cz.jiripinkas.jsitemapgenerator.exception.InvalidUrlException:
#    java.net.MalformedURLException:
#      Accessing a URL protocol that was not enabled. The URL protocol https is supported but not enabled by default.
#      It must be enabled by adding the --enable-url-protocols=https option to the native-image command.
quarkus.native.additional-build-args=--enable-url-protocols=https