<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.streamx.blueprints</groupId>
    <artifactId>processing</artifactId>
    <version>3.0.16-http</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>optimized-images-generator</artifactId>
  <name>StreamX Blueprints : Optimized Images Generator</name>

  <properties>
    <scrimage-webp.version>4.3.5</scrimage-webp.version>
    <maven-dependency-plugin.version>3.9.0</maven-dependency-plugin.version>
    <maven-antrun-plugin.version>3.2.0</maven-antrun-plugin.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.sksamuel.scrimage</groupId>
      <artifactId>scrimage-webp</artifactId>
      <version>${scrimage-webp.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <dependencies>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-awt</artifactId>
        </dependency>
      </dependencies>
      <build>
        <plugins>

          <!-- Extract scrimage webp libraries -->
          <plugin>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>${maven-dependency-plugin.version}</version>
            <executions>
              <execution>
                <id>unpack-binaries</id>
                <phase>prepare-package</phase>
                <goals>
                  <goal>unpack</goal>
                </goals>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>com.sksamuel.scrimage</groupId>
                      <artifactId>scrimage-webp</artifactId>
                      <includes>dist_webp_binaries/libwebp-*-linux-*/bin/*</includes>
                      <outputDirectory>${project.build.directory}/scrimage-webp-libraries</outputDirectory>
                    </artifactItem>
                  </artifactItems>
                </configuration>
              </execution>
            </executions>
          </plugin>

          <!-- Rename the extracted files for easier access via Dockerfile -->
          <plugin>
            <artifactId>maven-antrun-plugin</artifactId>
            <version>${maven-antrun-plugin.version}</version>
            <executions>
              <execution>
                <id>rename-binaries</id>
                <phase>prepare-package</phase>
                <configuration>
                  <target>
                    <move file="${project.build.directory}/scrimage-webp-libraries/dist_webp_binaries" tofile="${project.build.directory}/scrimage-webp-libraries/dist_webp_binaries">
                      <mapper type="regexp" from="(.*)x86-64(.*)" to="\1amd64\2" />
                    </move>
                    <move file="${project.build.directory}/scrimage-webp-libraries/dist_webp_binaries" tofile="${project.build.directory}/scrimage-webp-libraries/dist_webp_binaries">
                      <mapper type="regexp" from="(.*)aarch64(.*)" to="\1arm64\2" />
                    </move>
                  </target>
                </configuration>
                <goals>
                  <goal>run</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

</project>
