quarkus.otel.traces.exporter=none

mp.messaging.incoming.incoming-pages.connector=quarkus-websocket
mp.messaging.incoming.incoming-pages.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.incoming-pages.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.incoming-pages.path=/incoming-pages

mp.messaging.incoming.optimized-assets.connector=quarkus-websocket
mp.messaging.incoming.optimized-assets.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.optimized-assets.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.optimized-assets.path=/optimized-assets

mp.messaging.outgoing.adjusted-pages.connector=quarkus-websocket
mp.messaging.outgoing.adjusted-pages.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.outgoing.adjusted-pages.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.adjusted-pages.url=${STREAMX_ENDPOINT_ADJUSTED_PAGES}