quarkus.otel.traces.exporter=none

mp.messaging.incoming.incoming-pages.connector=quarkus-http
mp.messaging.incoming.incoming-pages.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.incoming-pages.path=/incoming-pages
mp.messaging.incoming.incoming-pages.protocolVersion=HTTP_2
mp.messaging.incoming.incoming-pages.twoPhaseResponseFlow=true

mp.messaging.incoming.optimized-assets.connector=quarkus-http
mp.messaging.incoming.optimized-assets.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.optimized-assets.path=/optimized-assets
mp.messaging.incoming.optimized-assets.protocolVersion=HTTP_2
mp.messaging.incoming.optimized-assets.twoPhaseResponseFlow=true

mp.messaging.outgoing.adjusted-pages.connector=quarkus-http
mp.messaging.outgoing.adjusted-pages.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.adjusted-pages.url=${STREAMX_ENDPOINT_ADJUSTED_PAGES}
mp.messaging.outgoing.adjusted-pages.protocolVersion=HTTP_2
mp.messaging.outgoing.adjusted-pages.twoPhaseResponseFlow=true
