PUT /_scripts/updateFragment
Content-Type: application/json

{
  "script": {
    "source": "for (fragment in ctx._source.fragments) { if (fragment.key == params.key && fragment.eventTime < params.eventTime) {fragment.eventTime = params.eventTime;fragment.payload = params.payload;}}",
    "lang": "painless"
  }
}
