mp.messaging.incoming.resources.connector=quarkus-http
mp.messaging.incoming.resources.deserializer=dev.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.resources.path=/resources

# web resources storage location
%dev.streamx.blueprints.web.resources.directory=./target/repository/resources

streamx.url-include-replacement-provider=SsiInclude