mp.messaging.incoming.resources.connector=quarkus-http
mp.messaging.incoming.resources.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.resources.path=/resources

# web resources storage location
%dev.streamx.blueprints.web.resources.directory=./target/repository/resources

streamx.url-include-replacement-provider=SsiInclude
streamx.blueprints.web.html-resource.types=dev.streamx.blueprints.page.published.v1,dev.streamx.blueprints.page.unpublished.v1