# Both Layout and Composition processing may produce PageComposeRequests
mp.messaging.outgoing.outgoing-page-compose-requests.merge=true

mp.messaging.incoming.layouts.connector=quarkus-http
mp.messaging.incoming.layouts.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.layouts.path=/layouts

mp.messaging.incoming.layouts-state.connector=quarkus-http
mp.messaging.incoming.layouts-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.layouts-state.path=/layouts-state

mp.messaging.incoming.compositions.connector=quarkus-http
mp.messaging.incoming.compositions.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.compositions.path=/compositions

mp.messaging.incoming.compositions-state.connector=quarkus-http
mp.messaging.incoming.compositions-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.compositions-state.path=/compositions-state

mp.messaging.outgoing.pages.connector=quarkus-http
mp.messaging.outgoing.pages.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.pages.url=${STREAMX_ENDPOINT_PAGES}

mp.messaging.incoming.incoming-page-compose-requests.connector=quarkus-http
mp.messaging.incoming.incoming-page-compose-requests.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.incoming-page-compose-requests.path=/incoming-page-compose-requests

mp.messaging.outgoing.outgoing-page-compose-requests.connector=quarkus-http
mp.messaging.outgoing.outgoing-page-compose-requests.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.outgoing-page-compose-requests.url=${STREAMX_ENDPOINT_OUTGOING_PAGE_COMPOSE_REQUESTS}