quarkus.otel.traces.exporter=none

mp.messaging.incoming.data.subscriptionName=json-aggregator-data
mp.messaging.incoming.multivalued-data.subscriptionName=json-aggregator-multivalued-data

mp.messaging.incoming.data.connector=quarkus-http
mp.messaging.incoming.data.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.data.path=/data
mp.messaging.incoming.data.protocolVersion=HTTP_2
mp.messaging.incoming.data.twoPhaseResponseFlow=true

mp.messaging.incoming.data-state.connector=quarkus-http
mp.messaging.incoming.data-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.data-state.path=/data-state
mp.messaging.incoming.data-state.protocolVersion=HTTP_2
mp.messaging.incoming.data-state.twoPhaseResponseFlow=true

mp.messaging.incoming.multivalued-data.connector=quarkus-http
mp.messaging.incoming.multivalued-data.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.multivalued-data.path=/multivalued-data
mp.messaging.incoming.multivalued-data.protocolVersion=HTTP_2
mp.messaging.incoming.multivalued-data.twoPhaseResponseFlow=true

mp.messaging.incoming.multivalued-data-state.connector=quarkus-http
mp.messaging.incoming.multivalued-data-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.multivalued-data-state.path=/multivalued-data-state
mp.messaging.incoming.multivalued-data-state.protocolVersion=HTTP_2
mp.messaging.incoming.multivalued-data-state.twoPhaseResponseFlow=true

mp.messaging.outgoing.aggregated-data.connector=quarkus-http
mp.messaging.outgoing.aggregated-data.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.aggregated-data.url=${STREAMX_ENDPOINT_AGGREGATED_DATA}
mp.messaging.outgoing.aggregated-data.protocolVersion=HTTP_2
mp.messaging.outgoing.aggregated-data.twoPhaseResponseFlow=true

mp.messaging.outgoing.aggregated-multivalued-data.connector=quarkus-http
mp.messaging.outgoing.aggregated-multivalued-data.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.aggregated-multivalued-data.url=${STREAMX_ENDPOINT_AGGREGATED_MULTIVALUED_DATA}
mp.messaging.outgoing.aggregated-multivalued-data.protocolVersion=HTTP_2
mp.messaging.outgoing.aggregated-multivalued-data.twoPhaseResponseFlow=true

