mp.messaging.incoming.data.subscriptionName=json-aggregator-data
mp.messaging.incoming.multivalued-data.subscriptionName=json-aggregator-multivalued-data

mp.messaging.incoming.data.connector=quarkus-http
mp.messaging.incoming.data.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.data.path=/data

mp.messaging.incoming.multivalued-data.connector=quarkus-http
mp.messaging.incoming.multivalued-data.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.multivalued-data.path=/multivalued-data

mp.messaging.outgoing.aggregated-data.connector=quarkus-http
mp.messaging.outgoing.aggregated-data.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.aggregated-data.url=${STREAMX_ENDPOINT_AGGREGATED_DATA}

mp.messaging.outgoing.aggregated-multivalued-data.connector=quarkus-http
mp.messaging.outgoing.aggregated-multivalued-data.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.aggregated-multivalued-data.url=${STREAMX_ENDPOINT_AGGREGATED_MULTIVALUED_DATA}

%dev.streamx.blueprints.json-aggregator.configurations[0].master-namespace=pim
%dev.streamx.blueprints.json-aggregator.configurations[0].optional-namespaces=price,reviews
%dev.streamx.blueprints.json-aggregator.configurations[0].output-namespace=product
%dev.streamx.blueprints.json-aggregator.configurations[1].master-namespace=review
%dev.streamx.blueprints.json-aggregator.configurations[1].output-namespace=reviews

