mp.messaging.incoming.data.subscriptionName=json-aggregator-data
mp.messaging.incoming.multivalued-data.subscriptionName=json-aggregator-multivalued-data

%dev.streamx.blueprints.json-aggregator.configurations[0].master-namespace=pim
%dev.streamx.blueprints.json-aggregator.configurations[0].optional-namespaces=price,reviews
%dev.streamx.blueprints.json-aggregator.configurations[0].output-namespace=product
%dev.streamx.blueprints.json-aggregator.configurations[1].master-namespace=review
%dev.streamx.blueprints.json-aggregator.configurations[1].output-namespace=reviews

%dev.mp.messaging.incoming.data.topic=persistent://public/default/data
%dev.mp.messaging.incoming.multivalued-data.topic=persistent://public/default/data
%dev.mp.messaging.outgoing.aggregated-data.topic=persistent://public/default/aggregated-data
%dev.mp.messaging.outgoing.aggregated-multivalued-data.topic=persistent://public/default/data


