quarkus.otel.traces.exporter=none

# multiple functions produce rendering-requests
mp.messaging.outgoing.outgoing-rendering-requests.merge=true

mp.messaging.incoming.data.connector=quarkus-http
mp.messaging.incoming.data.protocolVersion=HTTP_2
mp.messaging.incoming.data.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.data.path=/data

mp.messaging.incoming.data-state.connector=quarkus-http
mp.messaging.incoming.data-state.protocolVersion=HTTP_2
mp.messaging.incoming.data-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.data-state.path=/data-state

mp.messaging.incoming.renderers.connector=quarkus-http
mp.messaging.incoming.renderers.protocolVersion=HTTP_2
mp.messaging.incoming.renderers.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.renderers.path=/renderers

mp.messaging.incoming.renderers-state.connector=quarkus-http
mp.messaging.incoming.renderers-state.protocolVersion=HTTP_2
mp.messaging.incoming.renderers-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.renderers-state.path=/renderers-state

mp.messaging.incoming.rendering-contexts.connector=quarkus-http
mp.messaging.incoming.rendering-contexts.protocolVersion=HTTP_2
mp.messaging.incoming.rendering-contexts.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.rendering-contexts.path=/rendering-contexts

mp.messaging.incoming.rendering-contexts-state.connector=quarkus-http
mp.messaging.incoming.rendering-contexts-state.protocolVersion=HTTP_2
mp.messaging.incoming.rendering-contexts-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.rendering-contexts-state.path=/rendering-contexts-state

mp.messaging.incoming.incoming-rendering-requests.connector=quarkus-http
mp.messaging.incoming.incoming-rendering-requests.protocolVersion=HTTP_2
mp.messaging.incoming.incoming-rendering-requests.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.incoming-rendering-requests.path=/incoming-rendering-requests

mp.messaging.outgoing.outgoing-rendering-requests.connector=quarkus-http
mp.messaging.outgoing.outgoing-rendering-requests.protocolVersion=HTTP_2
mp.messaging.outgoing.outgoing-rendering-requests.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.outgoing-rendering-requests.url=${STREAMX_ENDPOINT_OUTGOING_RENDERING_REQUESTS}
mp.messaging.outgoing.outgoing-rendering-requests.maxInflightMessages=1000

mp.messaging.outgoing.pages.connector=quarkus-http
mp.messaging.outgoing.pages.protocolVersion=HTTP_2
mp.messaging.outgoing.pages.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.pages.url=${STREAMX_ENDPOINT_PAGES}
mp.messaging.outgoing.pages.maxInflightMessages=1000

mp.messaging.outgoing.fragments.connector=quarkus-http
mp.messaging.outgoing.fragments.protocolVersion=HTTP_2
mp.messaging.outgoing.fragments.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.fragments.url=${STREAMX_ENDPOINT_FRAGMENTS}
mp.messaging.outgoing.fragments.maxInflightMessages=1000
