# multiple functions produce rendering-requests
mp.messaging.outgoing.outgoing-rendering-requests.merge=true

%dev.mp.messaging.incoming.data.topic=persistent://streamx/relays/aggregated-data
%dev.mp.messaging.incoming.renderers.topic=persistent://streamx/inboxes/renderers
%dev.mp.messaging.incoming.rendering-contexts.topic=persistent://streamx/inboxes/rendering-contexts
%dev.mp.messaging.incoming.incoming-rendering-requests.topic=persistent://streamx/relays/rendering-requests
%dev.mp.messaging.outgoing.outgoing-rendering-requests.topic=persistent://streamx/relays/rendering-requests
%dev.mp.messaging.outgoing.pages.topic=persistent://streamx/inboxes/pages
%dev.mp.messaging.outgoing.fragments.topic=persistent://streamx/inboxes/fragments
