quarkus.otel.traces.exporter=none

# multiple functions produce rendering-requests
mp.messaging.outgoing.outgoing-rendering-requests.merge=true

mp.messaging.incoming.data.connector=quarkus-websocket
mp.messaging.incoming.data.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.data.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.data.path=/data

mp.messaging.incoming.data-state.connector=quarkus-websocket
mp.messaging.incoming.data-state.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.data-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.data-state.path=/data-state

mp.messaging.incoming.renderers.connector=quarkus-websocket
mp.messaging.incoming.renderers.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.renderers.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.renderers.path=/renderers

mp.messaging.incoming.renderers-state.connector=quarkus-websocket
mp.messaging.incoming.renderers-state.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.renderers-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.renderers-state.path=/renderers-state

mp.messaging.incoming.rendering-contexts.connector=quarkus-websocket
mp.messaging.incoming.rendering-contexts.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.rendering-contexts.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.rendering-contexts.path=/rendering-contexts

mp.messaging.incoming.rendering-contexts-state.connector=quarkus-websocket
mp.messaging.incoming.rendering-contexts-state.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.rendering-contexts-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.rendering-contexts-state.path=/rendering-contexts-state

mp.messaging.incoming.incoming-rendering-requests.connector=quarkus-websocket
mp.messaging.incoming.incoming-rendering-requests.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.incoming-rendering-requests.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.incoming-rendering-requests.path=/incoming-rendering-requests

mp.messaging.outgoing.outgoing-rendering-requests.connector=quarkus-websocket
mp.messaging.outgoing.outgoing-rendering-requests.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.outgoing.outgoing-rendering-requests.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.outgoing-rendering-requests.url=${STREAMX_ENDPOINT_OUTGOING_RENDERING_REQUESTS}

mp.messaging.outgoing.pages.connector=quarkus-websocket
mp.messaging.outgoing.pages.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.outgoing.pages.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.pages.url=${STREAMX_ENDPOINT_PAGES}

mp.messaging.outgoing.fragments.connector=quarkus-websocket
mp.messaging.outgoing.fragments.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.outgoing.fragments.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.fragments.url=${STREAMX_ENDPOINT_FRAGMENTS}
