quarkus.otel.traces.exporter=none

mp.messaging.incoming.incoming-assets.connector=quarkus-http
mp.messaging.incoming.incoming-assets.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.incoming-assets.path=/incoming-assets
mp.messaging.incoming.incoming-assets.protocolVersion=HTTP_2
mp.messaging.incoming.incoming-assets.twoPhaseResponseFlow=true

mp.messaging.outgoing.optimized-assets.connector=quarkus-http
mp.messaging.outgoing.optimized-assets.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.optimized-assets.url=${STREAMX_ENDPOINT_OPTIMIZED_ASSETS}
mp.messaging.outgoing.optimized-assets.protocolVersion=HTTP_2
mp.messaging.outgoing.optimized-assets.twoPhaseResponseFlow=true

# These classes must be initialized at runtime (since they read a system property in static init block) instead of while building the native image before running it
quarkus.native.additional-build-args=--initialize-at-run-time=com.sksamuel.scrimage