quarkus.otel.traces.exporter=none

mp.messaging.incoming.data.connector=quarkus-http
mp.messaging.incoming.data.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.data.path=/data

mp.messaging.incoming.data-state.connector=quarkus-http
mp.messaging.incoming.data-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.data-state.path=/data-state

mp.messaging.outgoing.collected-data.connector=quarkus-http
mp.messaging.outgoing.collected-data.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.collected-data.url=${STREAMX_ENDPOINT_COLLECTED_DATA}
mp.messaging.outgoing.collected-data.maxInflightMessages=1000

mp.messaging.outgoing.web-resources.connector=quarkus-http
mp.messaging.outgoing.web-resources.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.web-resources.url=${STREAMX_ENDPOINT_WEB_RESOURCES}
mp.messaging.outgoing.web-resources.maxInflightMessages=1000

streamx.blueprints.data-collector.dirty-check.interval=1s
streamx.blueprints.data-collector.dirty-check.max-dirty-sequence-count=5
streamx.blueprints.data-collector.dirty-check.delay=10s
