mp.messaging.incoming.data.connector=quarkus-http
mp.messaging.incoming.data.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.data.path=/data

mp.messaging.outgoing.collected-data.connector=quarkus-http
mp.messaging.outgoing.collected-data.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.collected-data.url=${STREAMX_ENDPOINT_COLLECTED_DATA}

mp.messaging.outgoing.web-resources.connector=quarkus-http
mp.messaging.outgoing.web-resources.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.web-resources.url=${STREAMX_ENDPOINT_WEB_RESOURCES}

streamx.blueprints.data-collector.dirty-check.interval=1s
streamx.blueprints.data-collector.dirty-check.max-dirty-sequence-count=5
streamx.blueprints.data-collector.dirty-check.delay=10s

%dev.streamx.blueprints.data-collector.web-resources.filters=collected:.*
%dev.streamx.blueprints.data-collector.web-resources.outgoing-prefix=_data/
%dev.streamx.blueprints.data-collector.configurations.cheapest-products-by-category.data-key-match-pattern=product:.*
%dev.streamx.blueprints.data-collector.configurations.cheapest-products-by-category.collector=aggregate-by-property-value
%dev.streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.output-key-prefix=collected:products:cheapest-by-category:
%dev.streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.group-by=category
%dev.streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.sort-by=price/value
%dev.streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.sort-mode=asc
%dev.streamx.blueprints.data-collector.configurations.cheapest-products-by-category.properties.max=8
%dev.mp.messaging.incoming.data.topic=persistent://streamx/relays/aggregated-data
%dev.mp.messaging.outgoing.collected-data.topic=persistent://streamx/relays/aggregated-data
%dev.mp.messaging.outgoing.web-resources.topic=persistent://streamx/inboxes/web-resources
