quarkus.otel.traces.exporter=none

mp.messaging.incoming.data.connector=quarkus-websocket
mp.messaging.incoming.data.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.data.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.data.path=/data

mp.messaging.incoming.data-state.connector=quarkus-websocket
mp.messaging.incoming.data-state.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.incoming.data-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.data-state.path=/data-state

mp.messaging.outgoing.collected-data.connector=quarkus-websocket
mp.messaging.outgoing.collected-data.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.outgoing.collected-data.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.collected-data.url=${STREAMX_ENDPOINT_COLLECTED_DATA}

mp.messaging.outgoing.web-resources.connector=quarkus-websocket
mp.messaging.outgoing.web-resources.message-id-provider=com.streamx.blueprints.cloudevents.utils.CloudEventMessageIdProvider
mp.messaging.outgoing.web-resources.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.web-resources.url=${STREAMX_ENDPOINT_WEB_RESOURCES}

streamx.blueprints.data-collector.dirty-check.interval=1s
streamx.blueprints.data-collector.dirty-check.max-dirty-sequence-count=5
streamx.blueprints.data-collector.dirty-check.delay=10s
