quarkus.otel.traces.exporter=none

mp.messaging.incoming.indexable-resources.connector=quarkus-http
mp.messaging.incoming.indexable-resources.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.indexable-resources.path=/indexable-resources
mp.messaging.incoming.indexable-resources.protocolVersion=HTTP_2
mp.messaging.incoming.indexable-resources.twoPhaseResponseFlow=true

mp.messaging.incoming.indexable-resources-state.connector=quarkus-http
mp.messaging.incoming.indexable-resources-state.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.indexable-resources-state.path=/indexable-resources-state
mp.messaging.incoming.indexable-resources-state.protocolVersion=HTTP_2
mp.messaging.incoming.indexable-resources-state.twoPhaseResponseFlow=true

mp.messaging.outgoing.transformations.connector=quarkus-http
mp.messaging.outgoing.transformations.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.transformations.url=${STREAMX_ENDPOINT_TRANSFORMATIONS}
mp.messaging.outgoing.transformations.protocolVersion=HTTP_2
mp.messaging.outgoing.transformations.twoPhaseResponseFlow=true

streamx.blueprints.indexable-resources-sql-transformer.dirty-check.interval=5s
streamx.blueprints.indexable-resources-sql-transformer.dirty-check.delay=10s
streamx.blueprints.indexable-resources-sql-transformer.dirty-check.max-dirty-sequence-count=12
