quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:./data/app.db

mp.messaging.incoming.indexable-resources.connector=quarkus-http
mp.messaging.incoming.indexable-resources.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.indexable-resources.path=/indexable-resources
mp.messaging.incoming.indexable-resources.protocolVersion=HTTP_2
mp.messaging.incoming.indexable-resources.twoPhaseResponseFlow=true

mp.messaging.outgoing.data.connector=quarkus-http
mp.messaging.outgoing.data.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.data.url=${STREAMX_ENDPOINT_DATA}
mp.messaging.outgoing.data.protocolVersion=HTTP_2
mp.messaging.outgoing.data.twoPhaseResponseFlow=true

quarkus.log.category."com.streamx.blueprints.sql".level=TRACE
quarkus.log.category."com.streamx.blueprints.sql".min-level=TRACE
