name: 'Test: Ubuntu CI native build'

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  native-test-build:
    runs-on: ubuntu-latest-l
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build project
        run: |
          ./mvnw clean verify -Dnative